# Generated by Django 5.0.1 on 2024-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activeid', models.IntegerField(blank=True, db_column='ActiveId', null=True)),
                ('personid', models.IntegerField(blank=True, db_column='PersonId', null=True)),
                ('pairid', models.IntegerField(blank=True, db_column='PairId', null=True)),
                ('dat', models.DateTimeField(blank=True, db_column='Dat', null=True)),
                ('grade', models.IntegerField(blank=True, db_column='Grade', null=True)),
            ],
            options={
                'db_table': 'active',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.IntegerField(blank=True, db_column='GroupID', null=True)),
                ('nam', models.CharField(blank=True, db_column='Nam', max_length=50, null=True)),
                ('course', models.IntegerField(blank=True, db_column='Course', null=True)),
            ],
            options={
                'db_table': 'groupa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('pairid', models.BigAutoField(db_column='PairId', primary_key=True, serialize=False)),
                ('teacherid', models.IntegerField(blank=True, db_column='TeacherId', null=True)),
                ('subjectid', models.IntegerField(blank=True, db_column='SubjectId', null=True)),
                ('typesubjectid', models.IntegerField(blank=True, db_column='TypeSubjectId', null=True)),
                ('nam', models.CharField(blank=True, db_column='Nam', max_length=50, null=True)),
                ('dat', models.DateTimeField(blank=True, db_column='Dat', null=True)),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
            ],
            options={
                'db_table': 'pair',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pairactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_id', models.PositiveBigIntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pairactive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('personid', models.BigAutoField(db_column='PersonID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('nickname', models.CharField(db_column='NickName', max_length=10)),
                ('groupid', models.IntegerField(blank=True, db_column='GroupID', null=True)),
                ('chatid', models.BigIntegerField(blank=True, db_column='ChatID', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=320, null=True)),
                ('status', models.IntegerField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectid', models.BigAutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('nam', models.CharField(blank=True, db_column='Nam', max_length=50, null=True)),
            ],
            options={
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.BigAutoField(db_column='TeacherID', primary_key=True, serialize=False)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('middlename', models.CharField(blank=True, db_column='MiddleName', max_length=50, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='JobTitle', max_length=50, null=True)),
                ('academicdegree', models.CharField(blank=True, db_column='AcademicDegree', max_length=50, null=True)),
                ('academictitle', models.CharField(blank=True, db_column='AcademicTitle', max_length=50, null=True)),
                ('chatid', models.IntegerField(blank=True, db_column='ChatID', null=True)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typeactive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nam', models.CharField(blank=True, db_column='Nam', max_length=50, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'typeactive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Typesubject',
            fields=[
                ('subjectid', models.BigAutoField(db_column='SubjectID', primary_key=True, serialize=False)),
                ('nam', models.CharField(blank=True, db_column='Nam', max_length=50, null=True)),
            ],
            options={
                'db_table': 'typesubject',
                'managed': False,
            },
        ),
    ]
