# Generated by Django 5.0.1 on 2024-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicJournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairactiv',
            name='idp',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pairactiv',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
