# Generated by Django 5.0.1 on 2024-03-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicJournal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
    ]
