# Generated by Django 5.0.1 on 2024-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicJournal', '0003_alter_teacher_options_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
    ]
