# Generated by Django 5.0.1 on 2024-03-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicJournal', '0004_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': True},
        ),
    ]
