# Generated by Django 5.0.1 on 2024-03-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicJournal', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='groupa',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pair',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pairactive',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='typeactive',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='typesubject',
            options={'managed': True},
        ),
    ]
